# Generated by Django 5.0 on 2023-12-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'статья', 'verbose_name_plural': 'статьи'},
        ),
        migrations.AddField(
            model_name='materials',
            name='count_view',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AddField(
            model_name='materials',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='дата создания'),
        ),
        migrations.AddField(
            model_name='materials',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='materials',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='materials',
            name='slug',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='слаг'),
        ),
    ]
