# Generated by Django 5.0 on 2023-12-22 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_materials_options_materials_count_view_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='изображение'),
        ),
    ]
