# Generated by Django 5.0 on 2024-01-09 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='index_version',
            new_name='active_version',
        ),
    ]
