# Generated by Django 5.0 on 2024-01-09 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_rename_index_version_version_active_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='active_version',
            field=models.BooleanField(default=False, verbose_name='признак текущей версии'),
        ),
    ]
