# Generated by Django 5.0 on 2024-01-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_version_active_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='active_version',
            field=models.BooleanField(choices=[(True, 'Активно'), (False, 'Неактивно')], default=False, verbose_name='признак текущей версии'),
        ),
    ]
