# Generated by Django 4.2 on 2024-01-20 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price_one',), 'permissions': [('can_change_is_published_permission', 'Can cancel product publication'), ('can_change_desc_permission', 'Can change product description'), ('can_change_category_permission', 'Can change product category')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
