# Generated by Django 4.2 on 2024-01-20 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price_one',), 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
